apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: YWRtaW4= # admin
  password: MWYyZDFlMmU2N2Rm # 1f2d1e2e67df

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "env" ] # print env var
      envFrom:
        - secretRef:
            name: mysecret
  restartPolicy: Never